# used for retriving arxiv data
FROM python:3.12-slim

# install arxiv and pandas
RUN pip install arxiv pandas tabulate feedparser

# Build the image with this command:
# docker build -f Dockerfile -t arxiv:latest .